### ISSUE TITLE
SeederAdmins

### ISSUE THREAD

**Issue by Aarabika** [AAArmand/QA_portal#7]
https://github.com/AAArmand/QA_portal/blob/30fdf9ddffec40cc5d776c9fdba9eab3c625a39d/database/seeds/SeederAdmins.php#L14

Пиши прямо тут какое имя, какой пароль, зачем на фабрику эту логику кидать?

**Comment by AAArmand** [comment]
https://github.com/AAArmand/QA_portal/blob/master/database/seeds/SeederAdmins.php

**Comment by AAArmand** [comment]
<?php

use Illuminate\Database\Seeder;

class SeederAdmins extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        factory(App\Models\Admin::class)->create([
            'login' => 'admin',
            'password' => password_hash('admin', PASSWORD_BCRYPT),
            'remember_token' => str_random(10)
        ]);
    }
}

**Comment by Aarabika** [comment]
https://github.com/AAArmand/QA_portal/blob/master/database/seeds/SeederAdmins.php#L14-L19

**Comment by AAArmand** [comment]
https://github.com/AAArmand/QA_portal/blob/master/database/seeds/SeederAdmins.php#L14-L17

**Comment by AAArmand** [comment]
https://github.com/AAArmand/QA_portal/blob/e79570e38b20b74a9806fb632c0f7bb671f1fbef/database/seeds/SeederAdmins.php#L14-L17

**Comment by Aarabika** [comment]
Без токена можешь, на кой он тебе?

**Comment by AAArmand** [comment]
там блять какая то залупа его просила

**Comment by AAArmand** [comment]
я уже не помню но там ошибку какую-то это исправляет

**Comment by Aarabika** [comment]
Та не может быть, в ларе токен генерится только когда галку жмешь, что мол запомнить меня, либо я что то не понимаю, либо ты неправ

**Comment by Aarabika** [comment]
https://stackoverflow.com/questions/23262351/laravel-remember-token

**Comment by AAArmand** [comment]
так у меня есть поле ремембер ми

**Comment by Aarabika** [comment]
Ну так токен нужен только если админ нажал запомнить меня, чтобы по нему авторизовываться

**Comment by Aarabika** [comment]
у тебя в базе будет токен, а в куках нет, тоесть бесполезно

**Comment by AAArmand** [comment]
https://github.com/AAArmand/QA_portal/blob/ee1db76ae2d6392c588ba7a173f6a9c8074d3824/database/seeds/SeederAdmins.php#L14-L16

**Comment by Aarabika** [comment]
Норм, закрываю
