### ISSUE TITLE
AdminFactory

### ISSUE THREAD

**Issue by Aarabika** [AAArmand/QA_portal#8]
https://github.com/AAArmand/QA_portal/blob/master/database/factories/AdminFactory.php

если я захочу сгенерить 1000 пользователей у тебя у всех будет один и тот же логин и пароль, ты скорее всего неправильно понял зачем нужны фабрики

**Comment by Aarabika** [comment]
В другой фабрике аналлогично

**Comment by AAArmand** [comment]
![adminfactory](https://user-images.githubusercontent.com/29011125/34780060-d8ca5066-f643-11e7-9649-a25d7804dbdb.PNG)
![questionfactory](https://user-images.githubusercontent.com/29011125/34780066-db30236c-f643-11e7-9bc4-e6d51d0dbdb2.PNG)

изменил

**Comment by Aarabika** [comment]
Нормально, закрываю
